#ifndef CPP_BASE_LIBRARY_SHUTDOWNPRIORITY_H
#define CPP_BASE_LIBRARY_SHUTDOWNPRIORITY_H

enum ShutdownPriority {
    DEFAULT = 0,
    PROCESS_SERVICE = 1,
};

#endif //CPP_BASE_LIBRARY_SHUTDOWNPRIORITY_H
